### ISSUE TITLE
reconnect error

### ISSUE THREAD

**Issue by shuxiongwei** [livekit/client-sdk-swift#844]
The default fast reconnection count is configured to 10 times. Why does it start from the beginning again after the 6th reconnection, starting from the 1st reconnection, and there is a high probability that it will fail to reconnect?

**Comment by pblazej** [comment]
@shuxiongwei could you share any more details/logs for this particular scenario? Is it a combination of quick/full reconnect attempts? Is it reproducible?

**Comment by shuxiongwei** [comment]
My SDK version is 2.8.1, and the maximum number of reconnections is 10, with a maximum retry interval of 4 seconds. This is the log printed during a voice call. There are two issues with reconnection after a disconnection:

1. If the network disconnection lasts for about 7-8 seconds and then is restored, a quick reconnection occurs, initially succeeding and the audio resumes. However, after about 3 seconds, a "transport disconnected" message appears, and then the reconnection process begins again. This issue is always reproducible.

2. If the network disconnection lasts for more than 10 seconds and then is restored, there's a high probability that reconnection will fail; occasionally, it may succeed.

I captured the log of the first successful reconnection, followed by an automatic disconnection shortly afterward; the network was normal during the entire process.

LiveKit 通话日志: 2025-11-18T11:26:49Z: debug Room.startReconnect(reason:nextReconnectMode:) [Connect] Starting retry attempt 6/10 with mode: .quick
LiveKit 通话日志: 2025-11-18T11:26:49Z: debug Room.quickReconnectSequence() [Connect] Starting .quick reconnect sequence...
LiveKit 通话日志: 2025-11-18T11:26:49Z: debug SignalClient.cleanUp(withError:) withError: nil
LiveKit 通话日志: 2025-11-18T11:26:49Z: debug SignalClient.connect(_:_:connectOptions:reconnectMode:participantSid:adaptiveStream:) [Connect] mode: .quick
LiveKit 通话日志: 2025-11-18T11:26:49Z: debug SignalClient.connect(_:_:connectOptions:reconnectMode:participantSid:adaptiveStream:) [Connect] with url: wss://livekit-test.mos.me/rtc?protocol=12&sdk=swift&version=2.8.1&os=iOS&os_version=26.0.1&device_model=iPhone14,5&network=wifi&reconnect=1&sid=PA_zekSnANMcWw2&auto_subscribe=1&adaptive_stream=1
LiveKit 通话日志: 2025-11-18T11:26:49Z: debug SignalClient.init() .disconnected -> .reconnecting
LiveKit 通话日志: 2025-11-18T11:26:49Z: debug ConnectivityListener.set(path:notify:) status: satisfied, interfaces: ["wifi-11", "wifi-11", "cellular-3"], gateways: [192.168.6.1:0], activeIp: Optional("192.168.6.125")
LiveKit 通话日志: 2025-11-18T11:26:49Z: debug ConnectivityListener.set(path:notify:) status: satisfied, interfaces: ["wifi-11", "wifi-11", "cellular-3"], gateways: [192.168.6.1:0], activeIp: Optional("192.168.6.125")
LiveKit 通话日志: 2025-11-18T11:26:49Z: debug AsyncCompleter<ConnectResponse>.wait(timeout:) Join response id: 32AD974C-D99B-4BCF-9CBA-080150BFCDDA waiting for milliseconds(7000)
LiveKit 通话日志: 2025-11-18T11:26:49Z: debug SignalClient.connect(_:_:connectOptions:reconnectMode:participantSid:adaptiveStream:) Did enter WebSocket message loop...
LiveKit 通话日志: 2025-11-18T11:26:49Z: debug SignalClient.init() .reconnecting -> .connected
LiveKit 通话日志: 2025-11-18T11:26:49Z: debug Room.configureTransports(connectResponse:) [Connect] Configuring transports with RECONNECT response...
LiveKit 通话日志: 2025-11-18T11:26:49Z: debug Room.quickReconnectSequence() [Connect] Waiting for subscriber to connect...
LiveKit 通话日志: 2025-11-18T11:26:49Z: debug Room.sendSyncState() trackSids: []
LiveKit 通话日志: 2025-11-18T11:26:49Z: debug Room.quickReconnectSequence() [Connect] Waiting for publisher to connect...
LiveKit 通话日志: 2025-11-18T11:26:49Z: debug Transport.createAndSendOffer(iceRestart:) Restarting ICE...
LiveKit 通话日志: 2025-11-18T11:26:49Z: debug Room.configureTransports(connectResponse:) Publisher onOffer v=0
LiveKit 通话日志: 2025-11-18T11:26:49Z: debug Room.configureTransports(connectResponse:) Publisher onOffer v=0
LiveKit 通话日志: 2025-11-18T11:26:49Z: debug Room.transport(_:didGenerateIceCandidate:) sending iceCandidate
LiveKit 通话日志: 2025-11-18T11:26:49Z: debug Room.transport(_:didGenerateIceCandidate:) sending iceCandidate
LiveKit 通话日志: 2025-11-18T11:26:49Z: debug Room.transport(_:didGenerateIceCandidate:) sending iceCandidate
LiveKit 通话日志: 2025-11-18T11:26:49Z: debug Room.startReconnect(reason:nextReconnectMode:) [Connect] Quick reconnect succeeded for attempt 6
LiveKit 通话日志: 2025-11-18T11:26:49Z: debug Room.startReconnect(reason:nextReconnectMode:) [Connect] Sequence completed
LiveKit 通话日志: 2025-11-18T11:26:49Z: debug Room.init(delegate:connectOptions:roomOptions:) connectionState: .connected -> .connected, reconnectMode: nil
LiveKit 通话日志: 2025-11-18T11:26:49Z: debug Room.signalClient(_:didUpdateParticipants:) participants: [LiveKitClient.Livekit_ParticipantInfo: sid: "PA_J6L95UpMBMSH" identity: "470525377279301" state: ACTIVE tracks {   sid: "TR_AMvaVxrCJ62iA2"   name: "microphone"   source: MICROPHONE   mime_type: "audio/red"   mid: "1"   stream: "camera"   version {     unix_micro: 1763465181774102   }   21: "{\"MimeType\":\"audio/red\",\"ClockRate\":48000,\"Channels\":2,\"SDPFmtpLine\":\"111/111\",\"RTCPFeedback\":null,\"PayloadType\":63}" } joined_at: 1763465179 version: 4 permission {   can_subscribe: true   can_publish: true   can_publish_data: true } is_publisher: true joined_at_ms: 1763465179507 , LiveKitClient.Livekit_ParticipantInfo: sid: "PA_zekSnANMcWw2" identity: "374526706554181" state: ACTIVE tracks {   sid: "TR_AMFwsDt4s4EQ64"   name: "microphone"   source: MICROPHONE   mime_type: "audio/red"   mid: "1"   stream: "camera"   version {     unix_micro: 1763465183330654   }   21: "{\"MimeType\":\"audio/red\",\"ClockRate\":48000,\"Channels\":2,\"SDPFmtpLine\":\"111/111\",\"RTCPFeedback\":null,\"PayloadType\":63}" } joined_at: 1763465180 version: 4 permission {   can_subscribe: true   can_publish: true   can_publish_data: true } is_publisher: true joined_at_ms: 1763465180959 ]
LiveKit 通话日志: 2025-11-18T11:26:49Z: debug Room.signalClient(_:didReceiveOffer:) Received offer, creating & sending answer...
LiveKit 通话日志: 2025-11-18T11:26:49Z: debug Room.transport(_:didGenerateIceCandidate:) sending iceCandidate
LiveKit 通话日志: 2025-11-18T11:26:49Z: debug Room.transport(_:didGenerateIceCandidate:) sending iceCandidate
LiveKit 通话日志: 2025-11-18T11:26:49Z: debug Room.transport(_:didGenerateIceCandidate:) sending iceCandidate
LiveKit 通话日志: 2025-11-18T11:26:49Z: debug Room.transport(_:didGenerateIceCandidate:) sending iceCandidate
LiveKit 通话日志: 2025-11-18T11:26:49Z: debug Room.transport(_:didGenerateIceCandidate:) sending iceCandidate
LiveKit 通话日志: 2025-11-18T11:26:49Z: debug Room.transport(_:didGenerateIceCandidate:) sending iceCandidate
LiveKit 通话日志: 2025-11-18T11:26:50Z: debug Room.transport(_:didGenerateIceCandidate:) sending iceCandidate
LiveKit 通话日志: 2025-11-18T11:26:50Z: debug Room.transport(_:didGenerateIceCandidate:) sending iceCandidate
LiveKit 通话日志: 2025-11-18T11:26:50Z: debug Room.transport(_:didGenerateIceCandidate:) sending iceCandidate
LiveKit 通话日志: 2025-11-18T11:26:50Z: debug Room.transport(_:didGenerateIceCandidate:) sending iceCandidate
LiveKit 通话日志: 2025-11-18T11:26:50Z: debug Room.transport(_:didGenerateIceCandidate:) sending iceCandidate
LiveKit 通话日志: 2025-11-18T11:26:50Z: debug Room.transport(_:didGenerateIceCandidate:) sending iceCandidate
LiveKit 通话日志: 2025-11-18T11:26:50Z: debug Room.transport(_:didGenerateIceCandidate:) sending iceCandidate
LiveKit 通话日志: 2025-11-18T11:26:50Z: debug Room.transport(_:didGenerateIceCandidate:) sending iceCandidate
LiveKit 通话日志: 2025-11-18T11:26:50Z: error Room.signalClient(_:didReceiveAnswer:) Failed to set remote description, error: Error Domain=org.webrtc.RTC_OBJC_TYPE(RTCPeerConnection) Code=-1 "Failed to set remote answer sdp: Called in wrong state: stable" UserInfo={NSLocalizedDescription=Failed to set remote answer sdp: Called in wrong state: stable}
LiveKit 通话日志: 2025-11-18T11:26:50Z: debug ConnectivityListener.set(path:notify:) status: satisfied, interfaces: ["wifi-11", "wifi-11", "cellular-3"], gateways: [192.168.6.1:0], activeIp: Optional("192.168.6.125")
LiveKit 通话日志: 2025-11-18T11:26:52Z: debug ConnectivityListener.set(path:notify:) status: satisfied, interfaces: ["wifi-11", "wifi-11", "cellular-3"], gateways: [192.168.6.1:0], activeIp: Optional("192.168.6.125")
LiveKit 通话日志: 2025-11-18T11:26:57Z: debug Transport.peerConnection(_:didChange:) [Connect] Transport(publisher) did update state: .disconnected
LiveKit 通话日志: 2025-11-18T11:26:57Z: debug Room.transport(_:didUpdateState:) target: publisher, connectionState: .disconnected
LiveKit 通话日志: 2025-11-18T11:26:57Z: debug Room.startReconnect(reason:nextReconnectMode:) [Connect] Starting, reason: transport
LiveKit 通话日志: 2025-11-18T11:26:57Z: debug Room.init(delegate:connectOptions:roomOptions:) connectionState: .connected -> .connected, reconnectMode: Optional(.quick)
LiveKit 通话日志: 2025-11-18T11:26:57Z: debug Room.startReconnect(reason:nextReconnectMode:) [Connect] Retry cycle waiting for 0.33 seconds before attempt 1
LiveKit 通话日志: 2025-11-18T11:26:57Z: debug Room.startReconnect(reason:nextReconnectMode:) [Connect] Starting retry attempt 1/10 with mode: .quick
LiveKit 通话日志: 2025-11-18T11:26:57Z: debug Room.quickReconnectSequence() [Connect] Starting .quick reconnect sequence...
LiveKit 通话日志: 2025-11-18T11:26:57Z: debug SignalClient.cleanUp(withError:) withError: nil
LiveKit 通话日志: 2025-11-18T11:26:57Z: debug SignalClient.init() .connected -> .disconnected

**Comment by pblazej** [comment]
Thank you for the logs, I pushed some hypothetical fix in the above PR ⏫ so you can try reproducing 👍

**Comment by shuxiongwei** [comment]
Did you only change this part? I tried it and the problem still exists.

<img width="2378" height="1014" alt="Image" src="https://github.com/user-attachments/assets/cb41ca46-dcac-4e4e-aef2-c51e7ef55a8f" />

**Comment by pblazej** [comment]
Yes, any difference in logs?

**Comment by shuxiongwei** [comment]
This will be printed.
log("Ignoring answer, signaling state is \(signalingState), expected .haveLocalOffer", .warning)

**Comment by pblazej** [comment]
I mean @shuxiongwei can you attach the logs from the new attempt (using the above branch)?

**Comment by shuxiongwei** [comment]
LiveKit 通话日志: 2025-11-18T13:21:24Z: debug Room.startReconnect(reason:nextReconnectMode:) [Connect] Starting retry attempt 5/10 with mode: .quick
LiveKit 通话日志: 2025-11-18T13:21:24Z: debug Room.quickReconnectSequence() [Connect] Starting .quick reconnect sequence...
LiveKit 通话日志: 2025-11-18T13:21:24Z: debug SignalClient.cleanUp(withError:) withError: nil
LiveKit 通话日志: 2025-11-18T13:21:24Z: debug SignalClient.connect(_:_:connectOptions:reconnectMode:participantSid:adaptiveStream:) [Connect] mode: .quick
LiveKit 通话日志: 2025-11-18T13:21:24Z: debug SignalClient.connect(_:_:connectOptions:reconnectMode:participantSid:adaptiveStream:) [Connect] with url: wss://livekit-test.mos.me/rtc?protocol=12&sdk=swift&version=2.8.1&os=iOS&os_version=26.0.1&device_model=iPhone14,5&network=wifi&reconnect=1&sid=PA_9pWs2iiDKMWW&auto_subscribe=1&adaptive_stream=1
LiveKit 通话日志: 2025-11-18T13:21:24Z: debug SignalClient.init() .disconnected -> .reconnecting
LiveKit 通话日志: 2025-11-18T13:21:24Z: debug SignalClient.connect(_:_:connectOptions:reconnectMode:participantSid:adaptiveStream:) Did enter WebSocket message loop...
LiveKit 通话日志: 2025-11-18T13:21:24Z: debug AsyncCompleter<ConnectResponse>.wait(timeout:) Join response id: 3A454EDD-3789-42FA-BF6F-4A5FB2BDB91D waiting for milliseconds(7000)
LiveKit 通话日志: 2025-11-18T13:21:24Z: debug SignalClient.init() .reconnecting -> .connected
LiveKit 通话日志: 2025-11-18T13:21:24Z: debug Room.configureTransports(connectResponse:) [Connect] Configuring transports with RECONNECT response...
LiveKit 通话日志: 2025-11-18T13:21:24Z: debug Room.quickReconnectSequence() [Connect] Waiting for subscriber to connect...
LiveKit 通话日志: 2025-11-18T13:21:24Z: debug Room.sendSyncState() trackSids: []
LiveKit 通话日志: 2025-11-18T13:21:24Z: debug Room.quickReconnectSequence() [Connect] Waiting for publisher to connect...
LiveKit 通话日志: 2025-11-18T13:21:24Z: debug Transport.createAndSendOffer(iceRestart:) Restarting ICE...
LiveKit 通话日志: 2025-11-18T13:21:24Z: debug Room.configureTransports(connectResponse:) Publisher onOffer v=0
LiveKit 通话日志: 2025-11-18T13:21:24Z: debug Room.transport(_:didGenerateIceCandidate:) sending iceCandidate
LiveKit 通话日志: 2025-11-18T13:21:24Z: debug Room.configureTransports(connectResponse:) Publisher onOffer v=0
LiveKit 通话日志: 2025-11-18T13:21:24Z: debug Room.transport(_:didGenerateIceCandidate:) sending iceCandidate
LiveKit 通话日志: 2025-11-18T13:21:24Z: debug Room.transport(_:didGenerateIceCandidate:) sending iceCandidate
LiveKit 通话日志: 2025-11-18T13:21:24Z: debug Room.startReconnect(reason:nextReconnectMode:) [Connect] Quick reconnect succeeded for attempt 5
LiveKit 通话日志: 2025-11-18T13:21:24Z: debug Room.startReconnect(reason:nextReconnectMode:) [Connect] Sequence completed
LiveKit 通话日志: 2025-11-18T13:21:24Z: debug Room.init(delegate:connectOptions:roomOptions:) connectionState: .connected -> .connected, reconnectMode: nil
LiveKit 通话日志: 2025-11-18T13:21:24Z: debug Room.signalClient(_:didUpdateParticipants:) participants: [LiveKitClient.Livekit_ParticipantInfo: sid: "PA_ZGoGFmKGprZc" identity: "470525377279301" state: ACTIVE tracks {   sid: "TR_AMzAHPcpiTByCF"   name: "microphone"   source: MICROPHONE   mime_type: "audio/red"   mid: "1"   stream: "camera"   version {     unix_micro: 1763471905225972   }   21: "{\"MimeType\":\"audio/red\",\"ClockRate\":48000,\"Channels\":2,\"SDPFmtpLine\":\"111/111\",\"RTCPFeedback\":null,\"PayloadType\":63}" } joined_at: 1763471903 version: 4 permission {   can_subscribe: true   can_publish: true   can_publish_data: true } is_publisher: true joined_at_ms: 1763471903258 , LiveKitClient.Livekit_ParticipantInfo: sid: "PA_9pWs2iiDKMWW" identity: "374526706554181" state: ACTIVE tracks {   sid: "TR_AMA37ntpbg6dyT"   name: "microphone"   source: MICROPHONE   mime_type: "audio/red"   mid: "1"   stream: "camera"   version {     unix_micro: 1763471910852332   }   21: "{\"MimeType\":\"audio/red\",\"ClockRate\":48000,\"Channels\":2,\"SDPFmtpLine\":\"111/111\",\"RTCPFeedback\":null,\"PayloadType\":63}" } joined_at: 1763471907 version: 4 permission {   can_subscribe: true   can_publish: true   can_publish_data: true } is_publisher: true joined_at_ms: 1763471907136 ]
LiveKit 通话日志: 2025-11-18T13:21:24Z: debug Room.signalClient(_:didReceiveOffer:) Received offer, creating & sending answer...
LiveKit 通话日志: 2025-11-18T13:21:24Z: debug Room.transport(_:didGenerateIceCandidate:) sending iceCandidate
LiveKit 通话日志: 2025-11-18T13:21:24Z: debug Room.transport(_:didGenerateIceCandidate:) sending iceCandidate
LiveKit 通话日志: 2025-11-18T13:21:24Z: debug Room.transport(_:didGenerateIceCandidate:) sending iceCandidate
LiveKit 通话日志: 2025-11-18T13:21:24Z: debug Room.transport(_:didGenerateIceCandidate:) sending iceCandidate
LiveKit 通话日志: 2025-11-18T13:21:24Z: debug Room.transport(_:didGenerateIceCandidate:) sending iceCandidate
LiveKit 通话日志: 2025-11-18T13:21:24Z: debug Room.transport(_:didGenerateIceCandidate:) sending iceCandidate
LiveKit 通话日志: 2025-11-18T13:21:24Z: debug Room.transport(_:didGenerateIceCandidate:) sending iceCandidate
LiveKit 通话日志: 2025-11-18T13:21:24Z: debug Room.transport(_:didGenerateIceCandidate:) sending iceCandidate
LiveKit 通话日志: 2025-11-18T13:21:24Z: debug Room.transport(_:didGenerateIceCandidate:) sending iceCandidate
LiveKit 通话日志: 2025-11-18T13:21:24Z: debug Room.transport(_:didGenerateIceCandidate:) sending iceCandidate
LiveKit 通话日志: 2025-11-18T13:21:24Z: debug Room.transport(_:didGenerateIceCandidate:) sending iceCandidate
LiveKit 通话日志: 2025-11-18T13:21:24Z: debug Room.transport(_:didGenerateIceCandidate:) sending iceCandidate
LiveKit 通话日志: 2025-11-18T13:21:25Z: debug Room.transport(_:didGenerateIceCandidate:) sending iceCandidate
LiveKit 通话日志: 2025-11-18T13:21:25Z: debug Room.transport(_:didGenerateIceCandidate:) sending iceCandidate
LiveKit 通话日志: 2025-11-18T13:21:25Z: warning Room.signalClient(_:didReceiveAnswer:) Ignoring answer, signaling state is LKRTCSignalingState(rawValue: 0), expected .haveLocalOffer
LiveKit 通话日志: 2025-11-18T13:21:25Z: debug ConnectivityListener.set(path:notify:) status: satisfied, interfaces: ["wifi-11", "wifi-11", "cellular-3"], gateways: [192.168.6.1:0], activeIp: Optional("192.168.6.125")
LiveKit 通话日志: 2025-11-18T13:21:26Z: debug ConnectivityListener.set(path:notify:) status: satisfied, interfaces: ["wifi-11", "wifi-11", "cellular-3"], gateways: [192.168.6.1:0], activeIp: Optional("192.168.6.125")
LiveKit 通话日志: 2025-11-18T13:21:27Z: debug ConnectivityListener.set(path:notify:) status: satisfied, interfaces: ["wifi-11", "wifi-11", "cellular-3"], gateways: [192.168.6.1:0], activeIp: Optional("192.168.6.125")
LiveKit 通话日志: 2025-11-18T13:21:28Z: debug ConnectivityListener.set(path:notify:) status: satisfied, interfaces: ["wifi-11", "wifi-11", "cellular-3"], gateways: [192.168.6.1:0], activeIp: Optional("192.168.6.125")
LiveKit 通话日志: 2025-11-18T13:21:30Z: debug Transport.peerConnection(_:didChange:) [Connect] Transport(publisher) did update state: .disconnected
LiveKit 通话日志: 2025-11-18T13:21:30Z: debug Room.transport(_:didUpdateState:) target: publisher, connectionState: .disconnected
LiveKit 通话日志: 2025-11-18T13:21:30Z: debug Room.startReconnect(reason:nextReconnectMode:) [Connect] Starting, reason: transport
LiveKit 通话日志: 2025-11-18T13:21:30Z: debug Room.init(delegate:connectOptions:roomOptions:) connectionState: .connected -> .connected, reconnectMode: Optional(.quick)
LiveKit 通话日志: 2025-11-18T13:21:30Z: debug Room.startReconnect(reason:nextReconnectMode:) [Connect] Retry cycle waiting for 0.32 seconds before attempt 1
LiveKit 通话日志: 2025-11-18T13:21:30Z: debug Room.startReconnect(reason:nextReconnectMode:) [Connect] Starting retry attempt 1/10 with mode: .quick
LiveKit 通话日志: 2025-11-18T13:21:30Z: debug Room.quickReconnectSequence() [Connect] Starting .quick reconnect sequence...
LiveKit 通话日志: 2025-11-18T13:21:30Z: debug SignalClient.cleanUp(withError:) withError: nil
LiveKit 通话日志: 2025-11-18T13:21:30Z: debug SignalClient.init() .connected -> .disconnected

**Comment by pblazej** [comment]
Thanks again, I think the root cause is known and requires a slightly bigger change in how we handle offers (duplicates, race conditions).

I'll keep you updated on this one @shuxiongwei

**Comment by shuxiongwei** [comment]
Hello, this issue significantly impacts audio and video call functionality, resulting in a very poor user experience. Please fix it as soon as possible. Thank you!

**Comment by shuxiongwei** [comment]
Hello, I found that the problem was closely related to the logic of this code. After commenting out the method indicated by the arrow in the screenshot, the problem was basically solved. However, if the network disconnection exceeds 15 seconds, it basically cannot reconnect.

<img width="2086" height="1714" alt="Image" src="https://github.com/user-attachments/assets/f71fb678-314a-48a3-8ce8-17aac0bc3392" />

**Comment by pblazej** [comment]
@shuxiongwei thank you for the hint, I think the issue is basically deeper in ICE handling. It's currently our top priority, so the fix should come soon.

**Comment by pblazej** [comment]
@shuxiongwei I updated the branch https://github.com/livekit/client-sdk-swift/pull/845

It would be great to test it, preferably with `.debug` logs [enabled](https://github.com/livekit/client-sdk-swift#how-to-adjust-the-log-level)

**Comment by shuxiongwei** [comment]
Hello, I've updated the code you modified yesterday, which resolved the issue of reconnecting successfully only to disconnect again after a 7-second network disconnection. However, I have a question: why are two offers being sent out simultaneously during fast reconnection? See the area indicated by the arrow in my screenshot:

<img width="3038" height="1730" alt="Image" src="https://github.com/user-attachments/assets/eb79560e-7633-44a2-b910-cc24e15f57f4" />

**Comment by shuxiongwei** [comment]
The problem persists: after a network outage of approximately 15 seconds and subsequent restoration, reconnection fails, as shown in the screenshot below:

<img width="2962" height="1754" alt="Image" src="https://github.com/user-attachments/assets/ee1a5215-0130-48f4-9a65-72d5d2176c99" />

**Comment by shuxiongwei** [comment]
I've noticed that after you've used up your quick reconnect attempts, if you still haven't reconnected, it will attempt a full reconnection, but the full reconnection will never succeed.

**Comment by pblazej** [comment]
@shuxiongwei thank you for testing 🤝 

I think there are multiple (new) issues uncovered here, related to these "duplicated" offers, as well as quick/full reconnect.

I updated the branch, so we can repeat the steps, hopefully 📶

**Comment by shuxiongwei** [comment]
Hello, regarding the code you updated yesterday, here are the results of my testing:

1. Submission 150e2c8e910aed0fb9b5614d4491a6ef33ab293e successfully resolved the issue of sending two offers consecutively during reconnection.

2. Submission 1fb19beca3c19cf0aa18b4efb4ac748acd660e86 attempted to initiate a full reconnection as early as possible, but this had no effect. Instead, it disrupted the logic that would normally allow for a quick and successful reconnection, ultimately resulting in a complete connection failure.

I previously discovered that after a network outage lasting longer than a certain period (it should start after 10 seconds, and definitely occur after 15 seconds), the quick reconnection method becomes ineffective. Even a full reconnection is useless because your full reconnection will always fail, regardless of the length of the outage, even if you attempt a full reconnection from the beginning. In other words, your full reconnection method is completely ineffective and will always fail.

why doesn't your full reconnection directly execute a method similar to the initial connection establishment: 
connect(url: String,
token: String,
connectOptions: ConnectOptions? = nil,
roomOptions: RoomOptions? = nil)

It seems your full reconnection only uses part of the logic from the initial connection.

I tried using the quick reconnect option, and when I entered the full reconnect phase, I commented out your full reconnect method and manually called connect, and the reconnection succeeded.

**Comment by pblazej** [comment]
@shuxiongwei let's try to sum up:
- double offer issue seems to be gone
- I reverted "faster full reconnect" in 09c0ac20d57344f77eceb0c33ab89cf77d3b9aa5
- also added more logs inside 5a1c6a8d94cb955214cd38b7281b991385d39203

Could you please attach these logs to make sure which part really fails in your case?

> the quick reconnection method becomes ineffective

**Comment by shuxiongwei** [comment]
Hello, I've encountered a major problem: When I updated your code to version 2.8.1, my own screen displayed correctly during video calls. However, after you resolved some of my other issues, I noticed a change in the logic. After updating to this commit 150e2c8e910aed0fb9b5614d4491a6ef33ab293e, my screen is no longer visible during video calls, although the other party can see it.

I urgently need your help with this issue. Thank you!

<img width="1404" height="290" alt="Image" src="https://github.com/user-attachments/assets/8696167d-f316-4b63-89d3-cf6b95f66c92" />

**Comment by pblazej** [comment]
@shuxiongwei I pushed some workaround here, you should be able to test the branch at least:
4c756c20e2c6c17463b41d20cb61008c0db7f617

**Comment by shuxiongwei** [comment]
Hello, upgrading to the commit you mentioned does indeed resolve the video call issue. However, I didn't have this problem in version 2.8.1. I see that you haven't changed any related code between version 2.8.1 and the latest commit. Why did that problem occur?

**Comment by pblazej** [comment]
It is probably related to this open issue https://github.com/livekit/client-sdk-swift/issues/843

**Comment by shuxiongwei** [comment]
Okay, thank you!

The issue I reported before still exists: your full reconnection method will never succeed.

**Comment by pblazej** [comment]
@shuxiongwei can you attach the logs please? (from this last attempt)

**Comment by shuxiongwei** [comment]
I set the fast reconnection count to 10 times, with a maximum time interval of 4 seconds. If the network connection is lost for more than 15 seconds and then restored, the 8th, 9th, and 10th fast reconnections will all fail, and then a full reconnection will be attempted, which will also fail. However, if I manually call the connect method to connect, it will succeed.

LiveKit 通话日志: 2025-11-25T11:16:02.861Z: Debug LiveKitClient/Room+Engine.swift startReconnect(reason:nextReconnectMode:) : [Connect] Starting retry attempt 10/10 with mode: .quick
LiveKit 通话日志: 2025-11-25T11:16:02.868Z: Debug LiveKitClient/Room.swift init(delegate:connectOptions:roomOptions:) : connectionState: .connected -> .connected, reconnectMode: Optional(.full)
nw_socket_copy_info [C170.1.1:3] Can't get TCP_INFO on a multipath socket
nw_socket_copy_info [C170.1.1:3] Can't get TCP_CONNECTION_INFO on a multipath socket
LiveKit 通话日志: 2025-11-25T11:16:02.872Z: Debug LiveKitClient/Room+Engine.swift fullReconnectSequence() : [Connect] starting .full reconnect sequence...
LiveKit 通话日志: 2025-11-25T11:16:02.876Z: Debug LiveKitClient/Room.swift init(delegate:connectOptions:roomOptions:) : connectionState: .connected -> .reconnecting, reconnectMode: Optional(.full)
LiveKit 通话日志: 2025-11-25T11:16:02.879Z: Debug LiveKitClient/Room.swift cleanUp(withError:isFullReconnect:) : withError: nil, isFullReconnect: true
LiveKit 通话日志: 2025-11-25T11:16:02.881Z: Debug LiveKitClient/SignalClient.swift cleanUp(withError:) : withError: nil
LiveKit 通话日志: 2025-11-25T11:16:02.884Z: Debug LiveKitClient/SignalClient.swift init() : .connected -> .disconnected
LiveKit 通话日志: 2025-11-25T11:16:02.886Z: Debug LiveKitClient/WebSocket.swift urlSession(_:task:didCompleteWithError:) : didCompleteWithError: nil
LiveKit 通话日志: 2025-11-25T11:16:02.889Z: Debug LiveKitClient/Room+Engine.swift cleanUpRTC() : [Connect] Cleaning up RTC resources
LiveKit 通话日志: 2025-11-25T11:16:02.891Z: Warning LiveKitClient/MetricsManager.swift sendMetrics(track:statistics:) : Failed to send metrics: Error Domain=io.livekit.swift-sdk Code=100 "Cancelled" UserInfo={NSLocalizedDescription=Cancelled}
LiveKit 通话日志: 2025-11-25T11:16:02.893Z: Warning LiveKitClient/MetricsManager.swift sendMetrics(track:statistics:) : Failed to send metrics: Error Domain=io.livekit.swift-sdk Code=100 "Cancelled" UserInfo={NSLocalizedDescription=Cancelled}
LiveKit 通话日志: 2025-11-25T11:16:02.894Z: Warning LiveKitClient/MetricsManager.swift sendMetrics(track:statistics:) : Failed to send metrics: Error Domain=io.livekit.swift-sdk Code=100 "Cancelled" UserInfo={NSLocalizedDescription=Cancelled}
LiveKit 通话日志: 2025-11-25T11:16:02.896Z: Warning LiveKitClient/MetricsManager.swift sendMetrics(track:statistics:) : Failed to send metrics: Error Domain=io.livekit.swift-sdk Code=100 "Cancelled" UserInfo={NSLocalizedDescription=Cancelled}
LiveKit 通话日志: 2025-11-25T11:16:02.898Z: Warning LiveKitClient/MetricsManager.swift sendMetrics(track:statistics:) : Failed to send metrics: Error Domain=io.livekit.swift-sdk Code=100 "Cancelled" UserInfo={NSLocalizedDescription=Cancelled}
LiveKit 通话日志: 2025-11-25T11:16:02.899Z: Warning LiveKitClient/MetricsManager.swift sendMetrics(track:statistics:) : Failed to send metrics: Error Domain=io.livekit.swift-sdk Code=100 "Cancelled" UserInfo={NSLocalizedDescription=Cancelled}
LiveKit 通话日志: 2025-11-25T11:16:02.900Z: Warning LiveKitClient/MetricsManager.swift sendMetrics(track:statistics:) : Failed to send metrics: Error Domain=io.livekit.swift-sdk Code=100 "Cancelled" UserInfo={NSLocalizedDescription=Cancelled}
LiveKit 通话日志: 2025-11-25T11:16:02.902Z: Warning LiveKitClient/MetricsManager.swift sendMetrics(track:statistics:) : Failed to send metrics: Error Domain=io.livekit.swift-sdk Code=100 "Cancelled" UserInfo={NSLocalizedDescription=Cancelled}
LiveKit 通话日志: 2025-11-25T11:16:02.903Z: Warning LiveKitClient/MetricsManager.swift sendMetrics(track:statistics:) : Failed to send metrics: Error Domain=io.livekit.swift-sdk Code=100 "Cancelled" UserInfo={NSLocalizedDescription=Cancelled}
LiveKit 通话日志: 2025-11-25T11:16:02.905Z: Warning LiveKitClient/MetricsManager.swift sendMetrics(track:statistics:) : Failed to send metrics: Error Domain=io.livekit.swift-sdk Code=100 "Cancelled" UserInfo={NSLocalizedDescription=Cancelled}
LiveKit 通话日志: 2025-11-25T11:16:02.906Z: Warning LiveKitClient/MetricsManager.swift sendMetrics(track:statistics:) : Failed to send metrics: Error Domain=io.livekit.swift-sdk Code=100 "Cancelled" UserInfo={NSLocalizedDescription=Cancelled}
LiveKit 通话日志: 2025-11-25T11:16:02.907Z: Warning LiveKitClient/MetricsManager.swift sendMetrics(track:statistics:) : Failed to send metrics: Error Domain=io.livekit.swift-sdk Code=100 "Cancelled" UserInfo={NSLocalizedDescription=Cancelled}
LiveKit 通话日志: 2025-11-25T11:16:02.908Z: Warning LiveKitClient/MetricsManager.swift sendMetrics(track:statistics:) : Failed to send metrics: Error Domain=io.livekit.swift-sdk Code=100 "Cancelled" UserInfo={NSLocalizedDescription=Cancelled}
LiveKit 通话日志: 2025-11-25T11:16:02.910Z: Warning LiveKitClient/MetricsManager.swift sendMetrics(track:statistics:) : Failed to send metrics: Error Domain=io.livekit.swift-sdk Code=100 "Cancelled" UserInfo={NSLocalizedDescription=Cancelled}
LiveKit 通话日志: 2025-11-25T11:16:02.911Z: Warning LiveKitClient/MetricsManager.swift sendMetrics(track:statistics:) : Failed to send metrics: Error Domain=io.livekit.swift-sdk Code=100 "Cancelled" UserInfo={NSLocalizedDescription=Cancelled}
LiveKit 通话日志: 2025-11-25T11:16:02.912Z: Warning LiveKitClient/MetricsManager.swift sendMetrics(track:statistics:) : Failed to send metrics: Error Domain=io.livekit.swift-sdk Code=100 "Cancelled" UserInfo={NSLocalizedDescription=Cancelled}
LiveKit 通话日志: 2025-11-25T11:16:02.913Z: Warning LiveKitClient/MetricsManager.swift sendMetrics(track:statistics:) : Failed to send metrics: Error Domain=io.livekit.swift-sdk Code=100 "Cancelled" UserInfo={NSLocalizedDescription=Cancelled}
LiveKit 通话日志: 2025-11-25T11:16:02.914Z: Warning LiveKitClient/MetricsManager.swift sendMetrics(track:statistics:) : Failed to send metrics: Error Domain=io.livekit.swift-sdk Code=100 "Cancelled" UserInfo={NSLocalizedDescription=Cancelled}
LiveKit 通话日志: 2025-11-25T11:16:02.915Z: Warning LiveKitClient/MetricsManager.swift sendMetrics(track:statistics:) : Failed to send metrics: Error Domain=io.livekit.swift-sdk Code=100 "Cancelled" UserInfo={NSLocalizedDescription=Cancelled}
LiveKit 通话日志: 2025-11-25T11:16:02.917Z: Warning LiveKitClient/MetricsManager.swift sendMetrics(track:statistics:) : Failed to send metrics: Error Domain=io.livekit.swift-sdk Code=100 "Cancelled" UserInfo={NSLocalizedDescription=Cancelled}
LiveKit 通话日志: 2025-11-25T11:16:02.918Z: Debug LiveKitClient/MixerEngineObserver.swift engineWillRelease(_:) : isManualRenderingMode: false
LiveKit 通话日志: 2025-11-25T11:16:02.985Z: Debug LiveKitClient/MixerEngineObserver.swift engineDidCreate(_:) : isManualRenderingMode: false
LiveKit 通话日志: 2025-11-25T11:16:03.003Z: Debug LiveKitClient/MixerEngineObserver.swift engineWillConnectOutput(_:src:dst:format:context:) : isManualRenderingMode: false
LiveKit 通话日志: 2025-11-25T11:16:03.094Z: Debug LiveKitClient/MixerEngineObserver.swift engineWillRelease(_:) : isManualRenderingMode: false
LiveKit 通话日志: 2025-11-25T11:16:03.096Z: Debug LiveKitClient/Room.swift cleanUpParticipants(isFullReconnect:notify:) : notify: true
LiveKit 通话日志: 2025-11-25T11:16:03.097Z: Error LiveKitClient/AsyncCompleter.swift resume(throwing:) : Participant active
LiveKit 通话日志: 2025-11-25T11:16:03.099Z: Debug LiveKitClient/AsyncCompleter.swift resume(with:) : Participant active already resolved [:] with success()
LiveKit 通话日志: 2025-11-25T11:16:03.102Z: Debug LiveKitClient/SignalClient.swift cleanUp(withError:) : withError: nil
LiveKit 通话日志: 2025-11-25T11:16:03.105Z: Debug LiveKitClient/SignalClient.swift connect(_:_:connectOptions:reconnectMode:participantSid:adaptiveStream:) : [Connect] mode: .full
LiveKit 通话日志: 2025-11-25T11:16:03.105Z: Debug LiveKitClient/SignalClient.swift connect(_:_:connectOptions:reconnectMode:participantSid:adaptiveStream:) : [Connect] with url: wss://livekit-test.mos.me/rtc?protocol=12&sdk=swift&version=2.10.0&os=iOS&os_version=26.0.1&device_model=iPhone15,3&network=wifi&auto_subscribe=1&adaptive_stream=1
LiveKit 通话日志: 2025-11-25T11:16:03.106Z: Debug LiveKitClient/SignalClient.swift init() : .disconnected -> .reconnecting
LiveKit 通话日志: 2025-11-25T11:16:03.107Z: Debug LiveKitClient/SignalClient.swift connect(_:_:connectOptions:reconnectMode:participantSid:adaptiveStream:) : [Connect] Opening SignalClient socket for reconnect
LiveKit 通话日志: 2025-11-25T11:16:06.149Z: Debug LiveKitClient/SignalClient.swift connect(_:_:connectOptions:reconnectMode:participantSid:adaptiveStream:) : [Connect] SignalClient socket ready in 3.05s
LiveKit 通话日志: 2025-11-25T11:16:06.155Z: Debug LiveKitClient/SignalClient.swift connect(_:_:connectOptions:reconnectMode:participantSid:adaptiveStream:) : [Connect] Waiting for reconnect response
LiveKit 通话日志: 2025-11-25T11:16:06.159Z: Debug LiveKitClient/SignalClient.swift connect(_:_:connectOptions:reconnectMode:participantSid:adaptiveStream:) : Did enter WebSocket message loop...
LiveKit 通话日志: 2025-11-25T11:16:06.162Z: Debug LiveKitClient/AsyncCompleter.swift wait(timeout:) : Join response id: BAF606FE-F6DE-4844-8B46-0C322269D786 waiting for milliseconds(7000)
LiveKit 通话日志: 2025-11-25T11:16:06.165Z: Debug LiveKitClient/SignalClient.swift _restartPingTimer() : ping/pong starting with interval: 5, timeout: 15
LiveKit 通话日志: 2025-11-25T11:16:06.168Z: Debug LiveKitClient/SignalClient.swift connect(_:_:connectOptions:reconnectMode:participantSid:adaptiveStream:) : [Connect] Reconnect response received in 0.00s
LiveKit 通话日志: 2025-11-25T11:16:06.170Z: Debug LiveKitClient/SignalClient.swift init() : .reconnecting -> .connected
LiveKit 通话日志: 2025-11-25T11:16:06.172Z: Debug LiveKitClient/Room+Engine.swift configureTransports(connectResponse:) : Configuring transports with JOIN response...
LiveKit 通话日志: 2025-11-25T11:16:06.175Z: Debug LiveKitClient/Room+Engine.swift configureTransports(connectResponse:) : subscriberPrimary: true
LiveKit 通话日志: 2025-11-25T11:16:06.177Z: Debug LiveKitClient/Transport.swift init(config:target:primary:delegate:) : 
LiveKit 通话日志: 2025-11-25T11:16:06.179Z: Debug LiveKitClient/Transport.swift init(config:target:primary:delegate:) : 
LiveKit 通话日志: 2025-11-25T11:16:06.180Z: Debug LiveKitClient/Transport.swift peerConnectionShouldNegotiate(_:) : ShouldNegotiate for publisher
LiveKit 通话日志: 2025-11-25T11:16:06.182Z: Debug LiveKitClient/Room+Engine.swift configureTransports(connectResponse:) : dataChannel.Optional("_reliable") : Optional(-1)
LiveKit 通话日志: 2025-11-25T11:16:06.184Z: Debug LiveKitClient/Room+Engine.swift configureTransports(connectResponse:) : dataChannel.Optional("_lossy") : Optional(-1)
LiveKit 通话日志: 2025-11-25T11:16:06.185Z: Debug LiveKitClient/Room+Engine.swift configureTransports(connectResponse:) : [Connect] Fast publish enabled: true
LiveKit 通话日志: 2025-11-25T11:16:06.187Z: Debug LiveKitClient/Room+Engine.swift publisherShouldNegotiate() : 
LiveKit 通话日志: 2025-11-25T11:16:06.189Z: Debug LiveKitClient/SignalClient.swift resumeQueues() : Resuming response/request queues
LiveKit 通话日志: 2025-11-25T11:16:06.190Z: Debug LiveKitClient/AsyncCompleter.swift wait(timeout:) : Primary transport connect id: 2F148CD6-19D6-4107-9540-946C90F29F00 waiting for milliseconds(10000)
LiveKit 通话日志: 2025-11-25T11:16:06.192Z: Debug LiveKitClient/Room+Engine.swift configureTransports(connectResponse:) : Publisher onOffer with offerId: 1, sdp: v=0
 o=- 5839105989736404807 2 IN IP4 127.0.0.1
 s=-
 t=0 0
 a=group:BUNDLE 0
 a=extmap-allow-mixed
 a=msid-semantic: WMS
 m=application 9 UDP/DTLS/SCTP webrtc-datachannel
 c=IN IP4 0.0.0.0
 a=ice-ufrag:3wgi
 a=ice-pwd:E8T/hzOFP9UHWm5xAdeZfHJF
 a=ice-options:trickle renomination
 a=fingerprint:sha-256 D0:27:88:5C:84:F3:2A:CA:A7:56:F8:6C:3D:D0:CB:19:50:B6:90:23:C9:B3:6D:E4:6B:26:FC:97:43:6C:F2:F8
 a=setup:actpass
 a=mid:0
 a=sctp-port:5000
 a=max-message-size:262144
 
LiveKit 通话日志: 2025-11-25T11:16:06.193Z: Debug LiveKitClient/Room+TransportDelegate.swift transport(_:didGenerateIceCandidate:) : sending iceCandidate
LiveKit 通话日志: 2025-11-25T11:16:06.290Z: Debug LiveKitClient/Room+TransportDelegate.swift transport(_:didGenerateIceCandidate:) : sending iceCandidate
LiveKit 通话日志: 2025-11-25T11:16:06.405Z: Debug LiveKitClient/Room+TransportDelegate.swift transport(_:didGenerateIceCandidate:) : sending iceCandidate
LiveKit 通话日志: 2025-11-25T11:16:16.230Z: Debug LiveKitClient/AsyncCompleter.swift wait(timeout:) : Primary transport connect id: 2F148CD6-19D6-4107-9540-946C90F29F00 timed out
nw_socket_copy_info [C171.1.1:3] Can't get TCP_INFO on a multipath socket
nw_socket_copy_info [C171.1.1:3] Can't get TCP_CONNECTION_INFO on a multipath socket
LiveKit 通话日志: 2025-11-25T11:16:16.237Z: Error LiveKitClient/Room+Engine.swift startReconnect(reason:nextReconnectMode:) : [Connect] Reconnect mode: .full failed with error: Error Domain=io.livekit.swift-sdk Code=101 "Timed out" UserInfo={NSLocalizedDescription=Timed out}
LiveKit 通话日志: 2025-11-25T11:16:16.243Z: Debug LiveKitClient/Room+Engine.swift startReconnect(reason:nextReconnectMode:) : [Connect] Sequence failed with error: Error Domain=io.livekit.swift-sdk Code=101 "Timed out" UserInfo={NSLocalizedDescription=Timed out}
LiveKit 通话日志: 2025-11-25T11:16:16.247Z: Debug LiveKitClient/Room.swift cleanUp(withError:isFullReconnect:) : withError: Optional(Error Domain=io.livekit.swift-sdk Code=101 "Timed out" UserInfo={NSLocalizedDescription=Timed out}), isFullReconnect: false
LiveKit 通话日志: 2025-11-25T11:16:16.249Z: Debug LiveKitClient/SignalClient.swift cleanUp(withError:) : withError: Optional(Error Domain=io.livekit.swift-sdk Code=101 "Timed out" UserInfo={NSLocalizedDescription=Timed out})
LiveKit 通话日志: 2025-11-25T11:16:16.252Z: Debug LiveKitClient/SignalClient.swift init() : .connected -> .disconnected
LiveKit 通话日志: 2025-11-25T11:16:16.256Z: Debug LiveKitClient/Room+Engine.swift cleanUpRTC() : [Connect] Cleaning up RTC resources
LiveKit 通话日志: 2025-11-25T11:16:16.258Z: Debug LiveKitClient/WebSocket.swift urlSession(_:task:didCompleteWithError:) : didCompleteWithError: nil
LiveKit 通话日志: 2025-11-25T11:16:16.261Z: Debug LiveKitClient/Room.swift cleanUpParticipants(isFullReconnect:notify:) : notify: true
LiveKit 通话日志: 2025-11-25T11:16:16.263Z: Debug LiveKitClient/Room.swift init(delegate:connectOptions:roomOptions:) : connectionState: .reconnecting -> .disconnected, reconnectMode: nil

**Comment by pblazej** [comment]
Thank you for the logs again @shuxiongwei 🥇 

I think we're moving closer to the root cause, I updated the branch once again 🔁

**Comment by shuxiongwei** [comment]
I noticed that your branch update doesn't include code to resolve full reconnection failures.

**Comment by pblazej** [comment]
@shuxiongwei could you be more specific? I think this is the commit that addresses the root cause abf2933e746cb25ec2c8e640e752afd1bd0c1123

**Comment by shuxiongwei** [comment]
Hello, the update still doesn't work, and it's not as effective as before. Previously, after network recovery, it would wait until the 10th quick reconnect before a full reconnection. Now, it directly performs a full reconnection on the 8th quick reconnection.

LiveKit 通话日志: 2025-11-26T08:27:37.680Z: Debug LiveKitClient/Room+Engine.swift startReconnect(reason:nextReconnectMode:) : [Connect] Starting retry attempt 8/10 with mode: .quick
LiveKit 通话日志: 2025-11-26T08:27:37.685Z: Debug LiveKitClient/Room.swift init(delegate:connectOptions:roomOptions:) : connectionState: .connected -> .connected, reconnectMode: Optional(.full)
LiveKit 通话日志: 2025-11-26T08:27:37.689Z: Debug LiveKitClient/Room+Engine.swift fullReconnectSequence() : [Connect] starting .full reconnect sequence...
LiveKit 通话日志: 2025-11-26T08:27:37.692Z: Debug LiveKitClient/Room.swift init(delegate:connectOptions:roomOptions:) : connectionState: .connected -> .reconnecting, reconnectMode: Optional(.full)
LiveKit 通话日志: 2025-11-26T08:27:37.694Z: Debug LiveKitClient/Room.swift cleanUp(withError:isFullReconnect:) : withError: nil, isFullReconnect: true
LiveKit 通话日志: 2025-11-26T08:27:37.697Z: Debug LiveKitClient/SignalClient.swift cleanUp(withError:) : withError: nil
LiveKit 通话日志: 2025-11-26T08:27:37.699Z: Warning LiveKitClient/MetricsManager.swift sendMetrics(track:statistics:) : Failed to send metrics: Error Domain=io.livekit.swift-sdk Code=100 "Cancelled" UserInfo={NSLocalizedDescription=Cancelled}
LiveKit 通话日志: 2025-11-26T08:27:37.702Z: Debug LiveKitClient/Room+Engine.swift cleanUpRTC() : [Connect] Cleaning up RTC resources
LiveKit 通话日志: 2025-11-26T08:27:37.704Z: Warning LiveKitClient/MetricsManager.swift sendMetrics(track:statistics:) : Failed to send metrics: Error Domain=io.livekit.swift-sdk Code=100 "Cancelled" UserInfo={NSLocalizedDescription=Cancelled}
LiveKit 通话日志: 2025-11-26T08:27:37.707Z: Warning LiveKitClient/MetricsManager.swift sendMetrics(track:statistics:) : Failed to send metrics: Error Domain=io.livekit.swift-sdk Code=100 "Cancelled" UserInfo={NSLocalizedDescription=Cancelled}
LiveKit 通话日志: 2025-11-26T08:27:37.709Z: Warning LiveKitClient/MetricsManager.swift sendMetrics(track:statistics:) : Failed to send metrics: Error Domain=io.livekit.swift-sdk Code=100 "Cancelled" UserInfo={NSLocalizedDescription=Cancelled}

**Comment by pblazej** [comment]
@shuxiongwei the next reconnect mode may be set to `.full` also when receiving a leave signal:

```swift
    func signalClient(_: SignalClient, didReceiveLeave canReconnect: Bool, reason: Livekit_DisconnectReason) async {
        log("canReconnect: \(canReconnect), reason: \(reason)")

        if canReconnect {
            // force .full for next reconnect
            _state.mutate { $0.nextReconnectMode = .full }
```

Is it 100% reproducible? I don't see the full logs from the failed full attempt here.

BTW, I updated the branch with one more change to be able to recover faster from this _leave_ scenario.

**Comment by shuxiongwei** [comment]
Hello, this issue is 100% reproducible. I'm using this commit: 199d70b1da00c845887e4f5b9b58081af2304097

As you can see in my previous comments, when entering the 8th fast reconnection, a full reconnection immediately begins, and then it fails to connect successfully.

Even if I set the fast reconnection count to 0 and directly enter a full reconnection, it still cannot connect successfully. The root cause is a problem with the full reconnection process. However, if I directly call the connect method, the reconnection succeeds.

**Comment by pblazej** [comment]
@shuxiongwei are you able to attach the full logs? Without that we're unable to recreate the order of events (both server and client side)

**Comment by shuxiongwei** [comment]
Hello, didn't I already post the logs for the 8th fast reconnection and full reconnection?

**Comment by pblazej** [comment]
Yes, but we need to know what happened before this: ` [Connect] Starting retry attempt 8/10 with mode: .quick`

Preferably, you can save a `.txt/.log` file from the whole run and attach here.
